# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: raveri
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: shopify-erp-serverless-integration
# "service" is the name of this project. This will also be added to your AWS resource names.
service: shopify-erp-serverless-integration

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  environment:
    ORDER_QUEUE_URL:
      Ref: OrderQueue
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - arn:aws:sqs:${self:provider.region}:${aws:accountId}:OrderQueue

functions:
  receiveWebhook:
    handler: handler.webhook
    events:
      - http:
          path: webhook/order
          method: post

  processOrder:
    handler: handler.processOrder
    events:
      - sqs:
          arn:
            Fn::GetAtt: [OrderQueue, Arn]

useDotenv: true

resources:
  Resources:
    OrderQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: OrderQueue

plugins:
  - serverless-offline
