# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: raveri
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: shopify-erp-serverless-integration
# "service" is the name of this project. This will also be added to your AWS resource names.
service: shopify-erp-serverless-integration

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  stage: dev
  environment:
    WEBHOOK_SIGNATURE: ${env:WEBHOOK_SIGNATURE}
    ORDER_QUEUE_URL:
      Ref: OrderQueue
    DYNAMODB_TABLE: OrderTable
    ERROR_ALERT_TOPIC_ARN:
      Ref: ErrorNotificationTopic
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - dynamodb:PutItem
        - dynamodb:GetItem
        - sns:Publish
      Resource:
        - arn:aws:sqs:${self:provider.region}:${aws:accountId}:OrderQueue
        - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/OrderTable
        - arn:aws:sns:${self:provider.region}:${aws:accountId}:lambda-error-notification-topic

functions:
  receiveWebhook:
    handler: src/handlers/handleWebhook.handler
    events:
      - http:
          path: webhook/order
          method: post

  processOrder:
    handler: src/handlers/processOrder.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [OrderQueue, Arn]

  errorNotifier:
    handler: src/handlers/notifyError.handler
    events:
      - cloudwatchLog:
          logGroup: /aws/lambda/${self:service}-${self:provider.stage}-processOrder
          filter: '"ERROR"'

useDotenv: true

resources:
  Resources:
    OrderQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: OrderQueue

    OrderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: OrderTable
        AttributeDefinitions:
          - AttributeName: orderId
            AttributeType: S
        KeySchema:
          - AttributeName: orderId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

    ErrorNotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: lambda-error-notification-topic

    ErrorNotificationSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: email
        Endpoint: lucaraveri993@gmail.com
        TopicArn:
          Ref: ErrorNotificationTopic
